run_id: evo-batch5_dep
overwrite: true

run_tasks:
  - dependency_maps

dataset:
  dataset_id: ribosome
  prepared_dir: data/prepared/ribosome
  start_record: 0
  end_record: 1
  
  
model:
  adapter: evo

  evo:
    model_name: evo-1-8k-base
    device: cuda:0



dependency_maps:
  mode: region
  batch_size: 1
  dependency_by_masking: false
  with_reconstruction: false

  region:
    label: 18S_rRNA
    record_ids:
      - Mammalia-Artiodactyla-Addax nasomaculatus-GCA_044231825-morph3

    long_region_policy: tile
    tile_length: 512
    tile_stride: 384

outputs_root: outputs/runs